name: Unit Test Job
on: [push]
jobs:
  unit-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ 1.17.13 ]
    steps:
      - run: echo "Unit test begin..."
      - run: go test -cover -covermode=atomic -gcflags=all=-l ./... -coverprofile=coverage.txt
      - run: go tool cover -func coverage.txt
      - run: bash <(curl -s https://codecov.io/bash)
      - run: echo "This job's status is ${{ job.status }}."